### ISSUE TITLE
Auto-detect changed file in dir?

### ISSUE THREAD

**Issue by whilei** [noraesae/pen#16]
I would love to see a feature where a directory is watched for changes to any of its files, and the browser would automatically update to show that file currently being edited. 

As in 
```
To be honest, you don't even need to launch it with a filename. You can manually open http://localhost:6060/README.md, or any other files in the same directory.
```
and those files in that `directory` would be watched, and changes to any of those files reflected in the browser. And since I'm only editing one file at once, I don't see too much of an issue with overlap.

Thanks for the awesome work already.

**Comment by noraesae** [comment]
This seems like a good idea. I'm currently not actively working on this project, but will absolutely accept contributions concerning this.
