### ISSUE TITLE
Support <table> tag

### ISSUE THREAD

**Issue by simnalamburt** [noraesae/pen#3]
Current `pen` implementation causes errors when I use table tag.

![image](https://cloud.githubusercontent.com/assets/4435445/16861193/81fa57da-4a79-11e6-8c21-ba8a8c08c538.png)

**Comment by noraesae** [comment]
현상은 확인 했는데, 원인을 아직 잘 모르겠습니다. 좀 더 보겠습니다.

이슈에서 다루는 문제는 아니지만 4번째로 나오는 에러는 react-render-html의 문제였고, 버전업을 하면서 해결 됐습니다. 이 저장소에도 react-render-html 버전업하는 패치를 올렸습니다. 9754d70a743d75d833928ac0fccfba20082cd981 신버전에서는 고쳐질 겁니다.

**Comment by noraesae** [comment]
0.1.3에서 수정되었습니다. 이슈 보고 감사드립니다.
