### ISSUE TITLE
Replace pug with another template engine with smaller dependencies

### ISSUE THREAD

**Issue by simnalamburt** [noraesae/pen#7]
[Pug] is not that fast, and has tons of dependencies. While we almost do not use Pug, it seems to be easy to replace it with faster and lighter template engine.

Currently I'm planning [doT.js]

###### References
- http://www.mikeperham.com/2016/02/09/kill-your-dependencies/

[Pug]: https://github.com/pugjs/pug
[very few]: https://github.com/noraesae/pen/blob/0ae537b59d833abdfd84131249abfb3b652717e3/src/template/preview.pug
[doT.js]: https://github.com/olado/doT

**Comment by noraesae** [comment]
How about using plain HTML with JS and CSS inlined?

**Comment by simnalamburt** [comment]
@noraesae Do you mean compiling the whole HTML inlining JS and CSS at compile time? That should be the most performant solution but it might bring a big change to the project structure. Is it OK?

**Comment by noraesae** [comment]
Continued in #7.
